### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by LeviRosol** [bencodrington/phanary#20]
Looks like the server is down. Any plans for it to come back up? I enjoy using this tool, so I'd be happy to help (hosting) if needed.

1. Which device and operating system are you using? OSX
2. Which browser are you using? Chrome
3. What did you do? Opened the site
4. What did you expect to see? The site
5. What did you see instead? 502 Bad Gateway

@bencodrington

**Comment by bencodrington** [comment]
Hi, thanks for notifying me!
Currently experiencing some server issues, but I am in the process of figuring it out.
With luck it should be back up and running in the next day or so.

**Comment by bencodrington** [comment]
The site should be up and running once again, so I'm closing this for now.
Please let me know if there are any more difficulties! Thanks.

**Comment by LeviRosol** [comment]
I didn't say it then, but wanted to stop back and say, thanks for bringing the site back up. I really enjoy using it in our campaigns!

**Comment by bencodrington** [comment]
Glad to hear it! Thanks for letting me know it was down =)
